
FROM python:3.11-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

EXPOSE 8181

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8181"]
